In [7]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import html5lib
import numpy as np
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time

In [8]:
URL_original = 'https://voz.vn/'

In [9]:
# Đường dẫn đến chromedriver (bạn tải tại https://chromedriver.chromium.org/)
options = Options()
# options.add_argument("--headless")  # Xóa dòng này nếu muốn thấy trình duyệt
driver = webdriver.Chrome(options=options)

# Truy cập Wikipedia
driver.get(URL_original)
time.sleep(5)  # Đợi trang tải xong (có thể điều chỉnh thời gian nếu cần)
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [10]:
link = soup.select('div.node-body')

In [11]:
link[0].select('a')[0]['href']

'/f/thong-bao.2/'

In [12]:
link_list = ['https://voz.vn/' + i.select('a')[0]['href'] for i in link]

In [13]:
link_list

['https://voz.vn//f/thong-bao.2/',
 'https://voz.vn//f/gop-y.3/',
 'https://voz.vn//s/tin-tuc-inet.102/',
 'https://voz.vn//s/review-san-pham.103/',
 'https://voz.vn//s/chia-se-kien-thuc.104/',
 'https://voz.vn//f/tu-van-cau-hinh.70/',
 'https://voz.vn//f/overclocking-cooling-modding.6/',
 'https://voz.vn//f/amd.25/',
 'https://voz.vn//f/intel.24/',
 'https://voz.vn//f/gpu-man-hinh.8/',
 'https://voz.vn//f/phan-cung-chung.9/',
 'https://voz.vn//f/thiet-bi-ngoai-vi-phu-kien-mang.30/',
 'https://voz.vn//f/server-nas-render-farm.83/',
 'https://voz.vn//f/small-form-factor-pc.61/',
 'https://voz.vn//f/hackintosh.62/',
 'https://voz.vn//f/may-tinh-xach-tay.47/',
 'https://voz.vn//f/phan-mem.13/',
 'https://voz.vn//f/app-di-dong.21/',
 'https://voz.vn//f/pc-gaming.11/',
 'https://voz.vn//f/console-gaming.22/',
 'https://voz.vn//f/android.32/',
 'https://voz.vn//f/apple.36/',
 'https://voz.vn//f/multimedia.31/',
 'https://voz.vn//f/do-dien-tu-thiet-bi-gia-dung.10/',
 'https://voz.vn//f/chup-anh-quay-phim.75/',
 'https://voz.vn//f/goc-chien-luoc.101/',
 'https://voz.vn//f/tuyen-dung-tim-viec.95/',
 'https://voz.vn//f/ngoai-ngu.90/',
 'https://voz.vn//f/lap-trinh-cntt.91/',
 'https://voz.vn//f/kinh-te-luat.92/',
 'https://voz.vn//f/make-money-online.93/',
 'https://voz.vn//f/tien-dien-tu.94/',
 'https://voz.vn//f/chuyen-tro-linh-tinh%E2%84%A2.17/',
 'https://voz.vn//f/diem-bao.33/',
 'https://voz.vn//f/4-banh.38/',
 'https://voz.vn//f/2-banh.39/',
 'https://voz.vn//f/the-duc-the-thao.63/',
 'https://voz.vn//f/am-thuc-du-lich.64/',
 'https://voz.vn//f/phim-nhac-sach.65/',
 'https://voz.vn//f/thoi-trang-lam-dep.66/',
 'https://voz.vn//f/cac-thu-choi-khac.67/',
 'https://voz.vn//f/may-tinh-de-ban.68/',
 'https://voz.vn//f/may-tinh-xach-tay.72/',
 'https://voz.vn//f/dien-thoai-di-dong.76/',
 'https://voz.vn//f/xe-cac-loai.77/',
 'https://voz.vn//f/thoi-trang-lam-dep.78/',
 'https://voz.vn//f/bat-dong-san.79/',
 'https://voz.vn//f/an-uong-du-lich.81/',
 'https://voz.vn//f/sim-so-do-phong-thuy.82/',
 'https://voz.vn//f/san-pham-dich-vu-khac.80/']

In [14]:
# Đường dẫn đến chromedriver (bạn tải tại https://chromedriver.chromium.org/)
options = Options()
# options.add_argument("--headless")  # Xóa dòng này nếu muốn thấy trình duyệt
driver = webdriver.Chrome(options=options)
driver.get(link_list[1])
time.sleep(5)
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [15]:
soup

<html class="has-js template-forum_view has-no-touchevents has-passiveeventlisteners has-no-hiddenscroll has-overflowanchor has-no-displaymodestandalone has-flexgap has-os-windows has-browser-chrome" data-app="public" data-color-scheme="light" data-container-key="node-3" data-content-key="forum-3" data-cookie-prefix="xf_" data-csrf="" data-logged-in="false" data-run-jobs="" data-template="forum_view" data-variation="default" data-xf="2.3" dir="LTR" id="XF" lang="en-US"><head>
<meta charset="utf-8"/>
<title>Góp ý | VOZ</title>
<link crossorigin="use-credentials" href="/webmanifest.php" rel="manifest"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1, viewport-fit=cover" name="viewport"/>
<meta content="#183254" name="theme-color"/>
<meta content="VOZ" name="apple-mobile-web-app-title"/>
<link href="/styles/next/xenforo/voz-logo-192.png?v=3" rel="apple-touch-icon"/>
<link href="https://voz.vn/f/gop-y.3/" rel="canonical"/>
<link href="/f/gop-y.3/index.rss" rel="alternate" title="RSS feed for Góp ý" type="application/rss+xml"/>
<link href="/f/gop-y.3/page-2" rel="next"/>
<meta content="VOZ" property="og:site_name"/>
<meta content="website" property="og:type"/>
<meta content="Góp ý" property="og:title"/>
<meta content="Góp ý" property="twitter:title"/>
<meta content="https://voz.vn//f/gop-y.3/" property="og:url"/>
<meta content="/styles/next/xenforo/voz-logo-og.png?v=3" property="og:image"/>
<meta content="/styles/next/xenforo/voz-logo-og.png?v=3" property="twitter:image"/>
<meta content="summary" property="twitter:card"/>
<script async="" src="/jc/gtm.js?_v=4d9940a3"></script>
<script>
		window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date);gtag('config','G-GJJX5F4EW5',{'style_id':4,'node_id':3,'node_title':'Góp ý','user_properties': {

		'pwa':navigator.standalone||window.matchMedia('(display-mode: standalone), (display-mode: minimal-ui)').matches?1:0,'user_group_id':1,
		},});
!function(b,c){"object"==typeof console&&"function"==typeof console.error&&(console.error_old=console.error,console.error=function(){console.error_old.apply(this,arguments);b.gtag("event","exception",{error_type:"console",error_message:arguments[0],fatal:!1})});b.onerror=function(a,d,e){b.gtag("event","exception",{error_type:"javascript",error_message:a,error_location:d,error_line_number:e,fatal:!1})};b.onload=function(){c.querySelectorAll("img").forEach(a=>{a.complete&&0===a.naturalWidth&&b.gtag("event",
"exception",{error_type:"image",error_message:"not_loaded",error_location:a.src,fatal:!1})})}}(window,document);
	</script>
<link href="/css.php?css=public%3Anormalize.css%2Cpublic%3Afa.css%2Cpublic%3Avariations.less%2Cpublic%3Acore.less%2Cpublic%3Aapp.less&amp;s=4&amp;l=1&amp;d=1772193144&amp;k=2d18b49606252d66328a9cbb81596deda239c85d" rel="stylesheet"/>
<link href="/css.php?css=public%3A000__page_container__head.less%2Cpublic%3Aprefix_menu.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Astructured_list.less%2Cpublic%3Axfes_suggested_threads.less%2Cpublic%3Aextra.less&amp;s=4&amp;l=1&amp;d=1772193144&amp;k=b1e9ade06ff0180abb5160e0ec1cca11bbb2bab1" rel="stylesheet"/>
<script src="/js/xf/preamble.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/vendor/vendor-compiled.js?_v=4d9940a3"></script>
<script defer="" src="/js/xf/core-compiled.js?_v=4d9940a3"></script>
<script>
	XF.samViewCountMethod = "view";
	XF.samServerTime = 1772726555;
	XF.samItem = ".samItem";
	XF.samCodeUnit = ".samCodeUnit";
	XF.samBannerUnit = ".samBannerUnit";
</script>
<script>
	window.addEventListener('DOMContentLoaded', () => {
		var bkp = document.querySelectorAll('div[data-ba]');
		if (bkp) {
			bkp.forEach(item => {
				var ad = item;
				if (ad.querySelector('ins.adsbygoogle').style.display == 'none') {
					 XF.ajax('GET', XF.canonicalizeUrl('index.php?sam-item/' + ad.dataset.ba + '/get-backup'), {}, data => {
						 if (data.backup) {
							 ad.html(data.backup);
						 }
					 }, { skipDefault: true, global: false});
				}
			});
		}
		const advHere = document.querySelectorAll('.samAdvertiseHereLink');
		if (advHere) {
			advHere.forEach(item => {
				var unit = item.parentNode;
				if (unit.classList.contains('samCustomSize')) {
					unit.style.marginBottom = 20;
				}
			});
		}
		const ff = document.querySelectorAll('div[data-position="footer_fixed"] > div[data-cv="true"]');
		if (ff) {
			ff.forEach(item => {
				XF.trigger(item, 'adView');
			});
		}
	});
</script>
<script>
		XF.ready(() =>
		{
			XF.extendObject(true, XF.config, {
				//
				userId: 0,
				enablePush: true,
				pushAppServerKey: 'BPPo5ZMIDnGRqO7goDiDVTGXpLgPpw3ftE3AekCNFLCHln2Sj+V+ogaGK/YWlAlTYrsc1Koz6WRkdCoEV0godEE=',
				url: {
					fullBase: 'https://voz.vn/',
					basePath: '/',
					css: '/css.php?css=__SENTINEL__&s=4&l=1&d=1772193144',
					js: '/js/__SENTINEL__?_v=4d9940a3',
					icon: '/data/local/icons/__VARIANT__.svg?v=1772193142#__NAME__',
					iconInline: '/styles/fa/__VARIANT__/__NAME__.svg?v=5.15.3',
					keepAlive: '/login/keep-alive'
				},
				cookie: {
					path: '/',
					domain: '',
					prefix: 'xf_',
					secure: true,
					consentMode: 'disabled',
					consented: ["optional","_third_party"]
				},
				cacheKey: '2a58ab23ecbe0c5111a37e7a0c221b19',
				csrf: '',
				js: {"\/js\/xf\/thread.min.js?_v=4d9940a3":true,"\/js\/xfes\/thread.min.js?_v=4d9940a3":true,"\/js\/xf\/prefix_menu.min.js?_v=4d9940a3":true},
				fullJs: false,
				css: {"public:000__page_container__head.less":true,"public:prefix_menu.less":true,"public:share_controls.less":true,"public:structured_list.less":true,"public:xfes_suggested_threads.less":true,"public:extra.less":true},
				time: {
					now: 1772726555,
					today: 1772643600,
					todayDow: 4,
					tomorrow: 1772730000,
					yesterday: 1772557200,
					week: 1772125200,
					month: 1772298000,
					year: 1767200400
				},
				style: {
					light: 'default',
					dark: 'alternate',
					defaultColorScheme: 'light'
				},
				borderSizeFeature: '3px',
				fontAwesomeWeight: 'r',
				enableRtnProtect: true,

				enableFormSubmitSticky: true,
				imageOptimization: 'optimize',
				imageOptimizationQuality: 0.85,
				uploadMaxFilesize: 67108864,
				uploadMaxWidth: 1600,
				uploadMaxHeight: 2400,
				allowedVideoExtensions: ["m4v","mov","mp4","mp4v","mpeg","mpg","ogv","webm"],
				allowedAudioExtensions: ["mp3","opus","ogg","wav"],
				shortcodeToEmoji: true,
				visitorCounts: {
					conversations_unread: '0',
					alerts_unviewed: '0',
					total_unread: '0',
					title_count: false,
					icon_indicator: true
				},
				jsMt: {"xf\/action.js":"b2d247ef","xf\/embed.js":"39c0fe7b","xf\/form.js":"39c0fe7b","xf\/structure.js":"b2d247ef","xf\/tooltip.js":"39c0fe7b"},
				jsState: {},
				publicMetadataLogoUrl: '/styles/next/xenforo/voz-logo-og.png?v=3',
				publicPushBadgeUrl: 'https://voz.vn/styles/default/xenforo/bell.png'
			})

			XF.extendObject(XF.phrases, {
				//
"time.day": "{count} day",
"time.days": "{count} days",
"time.hour": "{count} hour",
"time.hours": "{count} hours",
"time.minute": "{count} minute",
"time.minutes": "{count} minutes",
"time.month": "{count} month",
"time.months": "{count} months",
"time.second": "{count} second",
"time.seconds": "{count} seconds",
"time.week": "time.week",
"time.weeks": "{count} weeks",
"time.year": "{count} year",
"time.years": "{count} years",
				date_x_at_time_y:     "{date} at {time}",
				day_x_at_time_y:      "{day} at {time}",
				yesterday_at_x:       "Yesterday at {time}",
				x_minutes_ago:        "{minutes} minutes ago",
				one_minute_ago:       "1 minute ago",
				a_moment_ago:         "A moment ago",
				today_at_x:           "Today at {time}",
				in_a_moment:          "In a moment",
				in_a_minute:          "In a minute",
				in_x_minutes:         "In {minutes} minutes",
				later_today_at_x:     "Later today at {time}",
				tomorrow_at_x:        "Tomorrow at {time}",
				short_date_x_minutes: "{minutes}m",
				short_date_x_hours:   "{hours}h",
				short_date_x_days:    "{days}d",

				day0: "Sunday",
				day1: "Monday",
				day2: "Tuesday",
				day3: "Wednesday",
				day4: "Thursday",
				day5: "Friday",
				day6: "Saturday",

				dayShort0: "Sun",
				dayShort1: "Mon",
				dayShort2: "Tue",
				dayShort3: "Wed",
				dayShort4: "Thu",
				dayShort5: "Fri",
				dayShort6: "Sat",

				month0: "January",
				month1: "February",
				month2: "March",
				month3: "April",
				month4: "May",
				month5: "June",
				month6: "July",
				month7: "August",
				month8: "September",
				month9: "October",
				month10: "November",
				month11: "December",

				active_user_changed_reload_page: "The active user has changed. Reload the page for the latest version.",
				server_did_not_respond_in_time_try_again: "The server did not respond in time. Please try again.",
				oops_we_ran_into_some_problems: "Oops! We ran into some problems.",
				oops_we_ran_into_some_problems_more_details_console: "Oops! We ran into some problems. Please try again later. More error details may be in the browser console.",
				file_too_large_to_upload: "The file is too large to be uploaded.",
				uploaded_file_is_too_large_for_server_to_process: "The uploaded file is too large for the server to process.",
				files_being_uploaded_are_you_sure: "Files are still being uploaded. Are you sure you want to submit this form?",
				attach: "Attach files",
				rich_text_box: "Rich text box",
				close: "Close",
				link_copied_to_clipboard: "Link copied to clipboard.",
				text_copied_to_clipboard: "Text copied to clipboard.",
				loading: "Loading…",
				you_have_exceeded_maximum_number_of_selectable_items: "You have exceeded the maximum number of selectable items.",

				processing: "Processing",
				'processing...': "Processing…",

				showing_x_of_y_items: "Showing {count} of {total} items",
				showing_all_items: "Showing all items",
				no_items_to_display: "No items to display",

				number_button_up: "Increase",
				number_button_down: "Decrease",

				push_enable_notification_title: "Push notifications enabled successfully at VOZ",
				push_enable_notification_body: "Thank you for enabling push notifications!",

				pull_down_to_refresh: "Pull down to refresh",
				release_to_refresh: "Release to refresh",
				refreshing: "Refreshing…"
			})
		})

window.addEventListener('DOMContentLoaded',()=>{XF.on(document,"xf:reinit",(a)=>{if(a&&typeof(a)==='object'&&Object.prototype.toString.call(a)==='[object Event]'){if(typeof(a.target.querySelectorAll)==='function'){a.target.querySelectorAll(".overlay[data-url]:not([ga])").forEach(b=>{ b.setAttribute('ga',1);gtag("event","page_view",{page_title:b.querySelector(".overlay-title").textContent,page_location:b.getAttribute("data-url")})})}}})});document.querySelectorAll(".file-preview").forEach(filePreview=>{filePreview.addEventListener("click",()=>{gtag('event','file_download',{link_url:(new URL(filePreview.getAttribute("href"),window.location.origin)).href, file_name:filePreview.parentNode.querySelector('.file-name').textContent});});});document.querySelectorAll('.shareButtons-button').forEach(shareButton=>{shareButton.addEventListener('click',()=>{gtag('event','share',{method:shareButton.getAttribute('class').match(/.*shareButtons-button--(.*?)$|\s/)[1]});});});document.querySelectorAll('.bookmarkLink:not(.is-bookmarked)').forEach(bookmarkLink=>{bookmarkLink.addEventListener('click',()=>{gtag('event','bookmark');});});document.querySelectorAll(".js-installPromptButton").forEach(a=>{a.addEventListener("click",()=>{gtag("event","app_install_prompt")})});window.addEventListener("appinstalled",()=>{gtag("event","app_install")});XF.PWA&&XF.PWA.isRunning()&&document.addEventListener("visibilitychange",()=>{"visible"===document.visibilityState&&gtag("event","app_open")});setTimeout(()=>{document.querySelectorAll(".adsbygoogle").forEach(a=>{a.addEventListener("mouseenter",()=>{XF.aH=!0});a.addEventListener("mouseleave",()=>{XF.aH=!1});gtag("event","ads_impression",{ad_platform:"adsense"})});["pagehide","blur"].forEach(function(a){window.addEventListener(a,()=>{XF.aH&&gtag("event","ad_click",{ad_platform:"adsense"})},!1)})},3E3);


window.addEventListener('DOMContentLoaded',()=>{XF.Push.updateUserSubscriptionParent=XF.Push.updateUserSubscription;XF.Push.updateUserSubscription=function(b,a){"unsubscribe"===a&&XF.browser.safari&&XF.Push.setPushHistoryUserIds({});XF.Push.updateUserSubscriptionParent(b,a)}});
</script>
<script defer="" src="/js/xf/thread.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/xfes/thread.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/xf/prefix_menu.min.js?_v=4d9940a3"></script>
<link href="/styles/next/xenforo/voz-favicon.png?v=3" rel="icon" sizes="32x32" type="image/png"/>

In [16]:
pagination = soup.select('div.block-outer-main li.pageNav-page')

In [17]:
pagination

[<li class="pageNav-page pageNav-page--current"><a href="/f/gop-y.3/">1</a></li>,
 <li class="pageNav-page pageNav-page--later"><a href="/f/gop-y.3/page-2">2</a></li>,
 <li class="pageNav-page pageNav-page--later"><a href="/f/gop-y.3/page-3">3</a></li>,
 <li class="pageNav-page pageNav-page--skip pageNav-page--skipEnd">
 <a aria-expanded="false" aria-haspopup="true" aria-label="Go to page" data-original-title="Go to page" data-xf-click="menu" data-xf-init="tooltip" id="js-XFUniqueId1" role="button" tabindex="0">…</a>
 <div aria-hidden="true" class="menu menu--pageJump" data-menu="menu">
 <div class="menu-content">
 <h4 class="menu-header">Go to page</h4>
 <div class="menu-row" data-page-url="/f/gop-y.3/page-%page%" data-xf-init="page-jump">
 <div class="inputGroup inputGroup--numbers">
 <div class="inputGroup inputGroup--numbers inputNumber inputGroup--joined" data-xf-init="number-box"><input class="input input--number js-numberBoxTextInput input input--numberNarrow js-pageJumpPage" data-menu-autofocus="true" max="167" min="1" required="required" step="1" type="number" value="4"/><button aria-label="Increase" class="inputGroup-text inputNumber-button inputNumber-button--up js-up" data-dir="up" tabindex="-1" title="Increase" type="button"></button><button aria-label="Decrease" class="inputGroup-text inputNumber-button inputNumber-button--down js-down" data-dir="down" tabindex="-1" title="Decrease" type="button"></button></div>
 <span class="inputGroup-text"><button class="button js-pageJumpGo" type="button"><span class="button-text">Go</span></button></span>
 </div>
 </div>
 </div>
 </div>
 </li>,
 <li class="pageNav-page"><a href="/f/gop-y.3/page-167">167</a></li>,
 <li class="pageNav-page pageNav-page--current"><a href="/f/gop-y.3/">1</a></li>,
 <li class="pageNav-page pageNav-page--later"><a href="/f/gop-y.3/page-2">2</a></li>,
 <li class="pageNav-page pageNav-page--later"><a href="/f/gop-y.3/page-3">3</a></li>,
 <li class="pageNav-page pageNav-page--skip pageNav-page--skipEnd">
 <a aria-expanded="false" aria-haspopup="true" aria-label="Go to page" data-original-title="Go to page" data-xf-click="menu" data-xf-init="tooltip" id="js-XFUniqueId100" role="button" tabindex="0">…</a>
 <div aria-hidden="true" class="menu menu--pageJump" data-menu="menu">
 <div class="menu-content">
 <h4 class="menu-header">Go to page</h4>
 <div class="menu-row" data-page-url="/f/gop-y.3/page-%page%" data-xf-init="page-jump">
 <div class="inputGroup inputGroup--numbers">
 <div class="inputGroup inputGroup--numbers inputNumber inputGroup--joined" data-xf-init="number-box"><input class="input input--number js-numberBoxTextInput input input--numberNarrow js-pageJumpPage" data-menu-autofocus="true" max="167" min="1" required="required" step="1" type="number" value="4"/><button aria-label="Increase" class="inputGroup-text inputNumber-button inputNumber-button--up js-up" data-dir="up" tabindex="-1" title="Increase" type="button"></button><button aria-label="Decrease" class="inputGroup-text inputNumber-button inputNumber-button--down js-down" data-dir="down" tabindex="-1" title="Decrease" type="button"></button></div>
 <span class="inputGroup-text"><button class="button js-pageJumpGo" type="button"><span class="button-text">Go</span></button></span>
 </div>
 </div>
 </div>
 </div>
 </li>,
 <li class="pageNav-page"><a href="/f/gop-y.3/page-167">167</a></li>]

In [12]:
[i.select_one('a').text for i in pagination]

['1', '2', '3', '…', '167']

In [13]:
max_page = max([int(i.select_one('a').text) for i in pagination if i.select_one('a').text.isdigit()])

In [14]:
max_page

167

In [15]:
link_list_mini = ['https://voz.vn//f/gop-y.3/page-' + str(i) for i in range(1, max_page+1)]

In [23]:
link_list_mini[1]

'https://voz.vn//f/gop-y.3/page-2'

In [16]:
# Đường dẫn đến chromedriver (bạn tải tại https://chromedriver.chromium.org/)
options = Options()
# options.add_argument("--headless")  # Xóa dòng này nếu muốn thấy trình duyệt
driver = webdriver.Chrome(options=options)
driver.get(link_list_mini[1])
time.sleep(5)
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [24]:
soup.select('div.structItem-title')[0].select('a')[1].get('href')

'/t/loi-tra-mail-reset-pass.1193013/'

In [3]:
# Đường dẫn đến chromedriver (bạn tải tại https://chromedriver.chromium.org/)
options = Options()
# options.add_argument("--headless")  # Xóa dòng này nếu muốn thấy trình duyệt
driver = webdriver.Chrome(options=options)
driver.get('https://voz.vn/t/ho-tro-xac-thuc-tai-khoan.1149676/')
time.sleep(5)
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [4]:
soup

<html class="has-js template-thread_view has-no-touchevents has-passiveeventlisteners has-no-hiddenscroll has-overflowanchor has-no-displaymodestandalone has-flexgap has-os-windows has-browser-chrome" data-app="public" data-color-scheme="light" data-container-key="node-3" data-content-key="thread-1149676" data-cookie-prefix="xf_" data-csrf="" data-logged-in="false" data-template="thread_view" data-variation="default" data-xf="2.3" dir="LTR" id="XF" lang="en-US"><head>
<meta charset="utf-8"/>
<title>báo lỗi - Hỗ trợ xác thực tài khoản | VOZ</title>
<link crossorigin="use-credentials" href="/webmanifest.php" rel="manifest"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1, viewport-fit=cover" name="viewport"/>
<meta content="#183254" name="theme-color"/>
<meta content="VOZ" name="apple-mobile-web-app-title"/>
<link href="/styles/next/xenforo/voz-logo-192.png?v=3" rel="apple-touch-icon"/>
<meta content="Đã điền đầy đủ thông tin và nhắn cú pháp SMS những vẫn chưa đc xác thực, mod check giúp mình với" name="description"/>
<meta content="Đã điền đầy đủ thông tin và nhắn cú pháp SMS những vẫn chưa đc xác thực, mod check giúp mình với" property="og:description"/>
<meta content="Đã điền đầy đủ thông tin và nhắn cú pháp SMS những vẫn chưa đc xác thực, mod check giúp mình với" property="twitter:description"/>
<meta content="https://voz.vn/t/ho-tro-xac-thuc-tai-khoan.1149676/" property="og:url"/>
<link href="https://voz.vn/t/ho-tro-xac-thuc-tai-khoan.1149676/" rel="canonical"/>
<link href="/t/ho-tro-xac-thuc-tai-khoan.1149676/page-2" rel="next"/>
<meta content="VOZ" property="og:site_name"/>
<meta content="website" property="og:type"/>
<meta content="báo lỗi - Hỗ trợ xác thực tài khoản" property="og:title"/>
<meta content="báo lỗi - Hỗ trợ xác thực tài khoản" property="twitter:title"/>
<meta content="/styles/next/xenforo/voz-logo-og.png?v=3" property="og:image"/>
<meta content="/styles/next/xenforo/voz-logo-og.png?v=3" property="twitter:image"/>
<meta content="summary" property="twitter:card"/>
<script async="" src="/jc/gtm.js?_v=4d9940a3"></script>
<script>
		window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date);gtag('config','G-GJJX5F4EW5',{'style_id':4,'node_id':3,'node_title':'Góp ý','thread_id':1149676,'thread_title':'Hỗ trợ xác thực tài khoản','thread_prefix':'<span class=\"label label-\-red\" dir=\"auto\">báo lỗi<\/span><span class=\"label-append\">&nbsp;<\/span>','thread_author':'Uniquestz','user_properties': {

		'pwa':navigator.standalone||window.matchMedia('(display-mode: standalone), (display-mode: minimal-ui)').matches?1:0,'user_group_id':1,
		},});
!function(b,c){"object"==typeof console&&"function"==typeof console.error&&(console.error_old=console.error,console.error=function(){console.error_old.apply(this,arguments);b.gtag("event","exception",{error_type:"console",error_message:arguments[0],fatal:!1})});b.onerror=function(a,d,e){b.gtag("event","exception",{error_type:"javascript",error_message:a,error_location:d,error_line_number:e,fatal:!1})};b.onload=function(){c.querySelectorAll("img").forEach(a=>{a.complete&&0===a.naturalWidth&&b.gtag("event",
"exception",{error_type:"image",error_message:"not_loaded",error_location:a.src,fatal:!1})})}}(window,document);
	</script>
<link href="/css.php?css=public%3Anormalize.css%2Cpublic%3Afa.css%2Cpublic%3Avariations.less%2Cpublic%3Acore.less%2Cpublic%3Aapp.less&amp;s=4&amp;l=1&amp;d=1772193144&amp;k=2d18b49606252d66328a9cbb81596deda239c85d" rel="stylesheet"/>
<link href="/css.php?css=public%3A000__page_container__head.less%2Cpublic%3Aattachments.less%2Cpublic%3Abb_code.less%2Cpublic%3Aeditor.less%2Cpublic%3Alightbox.less%2Cpublic%3Amessage.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Astructured_list.less%2Cpublic%3AsvLazyImageLoader.less%2Cpublic%3Aextra.less&amp;s=4&amp;l=1&amp;d=1772193144&amp;k=8aab4ef63417528b812f04dcdade71e78a79435f" rel="stylesheet"/>
<script src="/js/xf/preamble.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/vendor/vendor-compiled.js?_v=4d9940a3"></script>
<script defer="" src="/js/xf/core-compiled.js?_v=4d9940a3"></script>
<script>
	XF.samViewCountMethod = "view";
	XF.samServerTime = 1772378648;
	XF.samItem = ".samItem";
	XF.samCodeUnit = ".samCodeUnit";
	XF.samBannerUnit = ".samBannerUnit";
</script>
<script>
	window.addEventListener('DOMContentLoaded', () => {
		var bkp = document.querySelectorAll('div[data-ba]');
		if (bkp) {
			bkp.forEach(item => {
				var ad = item;
				if (ad.querySelector('ins.adsbygoogle').style.display == 'none') {
					 XF.ajax('GET', XF.canonicalizeUrl('index.php?sam-item/' + ad.dataset.ba + '/get-backup'), {}, data => {
						 if (data.backup) {
							 ad.html(data.backup);
						 }
					 }, { skipDefault: true, global: false});
				}
			});
		}
		const advHere = document.querySelectorAll('.samAdvertiseHereLink');
		if (advHere) {
			advHere.forEach(item => {
				var unit = item.parentNode;
				if (unit.classList.contains('samCustomSize')) {
					unit.style.marginBottom = 20;
				}
			});
		}
		const ff = document.querySelectorAll('div[data-position="footer_fixed"] > div[data-cv="true"]');
		if (ff) {
			ff.forEach(item => {
				XF.trigger(item, 'adView');
			});
		}
	});
</script>
<script>
		XF.ready(() =>
		{
			XF.extendObject(true, XF.config, {
				//
				userId: 0,
				enablePush: true,
				pushAppServerKey: 'BPPo5ZMIDnGRqO7goDiDVTGXpLgPpw3ftE3AekCNFLCHln2Sj+V+ogaGK/YWlAlTYrsc1Koz6WRkdCoEV0godEE=',
				url: {
					fullBase: 'https://voz.vn/',
					basePath: '/',
					css: '/css.php?css=__SENTINEL__&s=4&l=1&d=1772193144',
					js: '/js/__SENTINEL__?_v=4d9940a3',
					icon: '/data/local/icons/__VARIANT__.svg?v=1772193142#__NAME__',
					iconInline: '/styles/fa/__VARIANT__/__NAME__.svg?v=5.15.3',
					keepAlive: '/login/keep-alive'
				},
				cookie: {
					path: '/',
					domain: '',
					prefix: 'xf_',
					secure: true,
					consentMode: 'disabled',
					consented: ["optional","_third_party"]
				},
				cacheKey: '2a58ab23ecbe0c5111a37e7a0c221b19',
				csrf: '',
				js: {"\/js\/xf\/lightbox-compiled.js?_v=4d9940a3":true,"\/js\/sv\/lazyimageloader\/xf\/lightbox.min.js?_v=4d9940a3":true,"\/js\/sv\/lazyimageloader\/lazy-compiled.js?_v=4d9940a3":true,"\/js\/xf\/action.min.js?_v=4d9940a3":true,"\/js\/xf\/message.min.js?_v=4d9940a3":true,"\/js\/xf\/captcha.min.js?_v=4d9940a3":true,"\/js\/xf\/editor-compiled.js?_v=4d9940a3":true},
				fullJs: false,
				css: {"public:000__page_container__head.less":true,"public:attachments.less":true,"public:bb_code.less":true,"public:editor.less":true,"public:lightbox.less":true,"public:message.less":true,"public:share_controls.less":true,"public:structured_list.less":true,"public:svLazyImageLoader.less":true,"public:extra.less":true},
				time: {
					now: 1772378648,
					today: 1772298000,
					todayDow: 0,
					tomorrow: 1772384400,
					yesterday: 1772211600,
					week: 1771779600,
					month: 1772298000,
					year: 1767200400
				},
				style: {
					light: 'default',
					dark: 'alternate',
					defaultColorScheme: 'light'
				},
				borderSizeFeature: '3px',
				fontAwesomeWeight: 'r',
				enableRtnProtect: true,

				enableFormSubmitSticky: true,
				imageOptimization: 'optimize',
				imageOptimizationQuality: 0.85,
				uploadMaxFilesize: 67108864,
				uploadMaxWidth: 1600,
				uploadMaxHeight: 2400,
				allowedVideoExtensions: ["m4v","mov","mp4","mp4v","mpeg","mpg","ogv","webm"],
				allowedAudioExtensions: ["mp3","opus","ogg","wav"],
				shortcodeToEmoji: true,
				visitorCounts: {
					conversations_unread: '0',
					alerts_unviewed: '0',
					total_unread: '0',
					title_count: false,
					icon_indicator: true
				},
				jsMt: {"xf\/action.js":"b2d247ef","xf\/embed.js":"39c0fe7b","xf\/form.js":"39c0fe7b","xf\/structure.js":"b2d247ef","xf\/tooltip.js":"39c0fe7b"},
				jsState: {},
				publicMetadataLogoUrl: '/styles/next/xenforo/voz-logo-og.png?v=3',
				publicPushBadgeUrl: 'https://voz.vn/styles/default/xenforo/bell.png'
			})

			XF.extendObject(XF.phrases, {
				//
"time.day": "{count} day",
"time.days": "{count} days",
"time.hour": "{count} hour",
"time.hours": "{count} hours",
"time.minute": "{count} minute",
"time.minutes": "{count} minutes",
"time.month": "{count} month",
"time.months": "{count} months",
"time.second": "{count} second",
"time.seconds": "{count} seconds",
"time.week": "time.week",
"time.weeks": "{count} weeks",
"time.year": "{count} year",
"time.years": "{count} years",
				date_x_at_time_y:     "{date} at {time}",
				day_x_at_time_y:      "{day} at {time}",
				yesterday_at_x:       "Yesterday at {time}",
				x_minutes_ago:        "{minutes} minutes ago",
				one_minute_ago:       "1 minute ago",
				a_moment_ago:         "A moment ago",
				today_at_x:           "Today at {time}",
				in_a_moment:          "In a moment",
				in_a_minute:          "In a minute",
				in_x_minutes:         "In {minutes} minutes",
				later_today_at_x:     "Later today at {time}",
				tomorrow_at_x:        "Tomorrow at {time}",
				short_date_x_minutes: "{minutes}m",
				short_date_x_hours:   "{hours}h",
				short_date_x_days:    "{days}d",

				day0: "Sunday",
				day1: "Monday",
				day2: "Tuesday",
				day3: "Wednesday",
				day4: "Thursday",
				day5: "Friday",
				day6: "Saturday",

				dayShort0: "Sun",
				dayShort1: "Mon",
				dayShort2: "Tue",
				dayShort3: "Wed",
				dayShort4: "Thu",
				dayShort5: "Fri",
				dayShort6: "Sat",

				month0: "January",
				month1: "February",
				month2: "March",
				month3: "April",
				month4: "May",
				month5: "June",
				month6: "July",
				month7: "August",
				month8: "September",
				month9: "October",
				month10: "November",
				month11: "December",

				active_user_changed_reload_page: "The active user has changed. Reload the page for the latest version.",
				server_did_not_respond_in_time_try_again: "The server did not respond in time. Please try again.",
				oops_we_ran_into_some_problems: "Oops! We ran into some problems.",
				oops_we_ran_into_some_problems_more_details_console: "Oops! We ran into some problems. Please try again later. More error details may be in the browser console.",
				file_too_large_to_upload: "The file is too large to be uploaded.",
				uploaded_file_is_too_large_for_server_to_process: "The uploaded file is too large for the server to process.",
				files_being_uploaded_are_you_sure: "Files are still being uploaded. Are you sure you want to submit this form?",
				attach: "Attach files",
				rich_text_box: "Rich text box",
				close: "Close",
				link_copied_to_clipboard: "Link copied to clipboard.",
				text_copied_to_clipboard: "Text copied to clipboard.",
				loading: "Loading…",
				you_have_exceeded_maximum_number_of_selectable_items: "You have exceeded the maximum number of selectable items.",

				processing: "Processing",
				'processing...': "Processing…",

				showing_x_of_y_items: "Showing {count} of {total} items",
				showing_all_items: "Showing all items",
				no_items_to_display: "No items to display",

				number_button_up: "Increase",
				number_button_down: "Decrease",

				push_enable_notification_title: "Push notifications enabled successfully at VOZ",
				push_enable_notification_body: "Thank you for enabling push notifications!",

				pull_down_to_refresh: "Pull down to refresh",
				release_to_refresh: "Release to refresh",
				refreshing: "Refreshing…"
			})
		})

window.addEventListener('DOMContentLoaded',()=>{XF.on(document,"xf:reinit",(a)=>{if(a&&typeof(a)==='object'&&Object.prototype.toString.call(a)==='[object Event]'){if(typeof(a.target.querySelectorAll)==='function'){a.target.querySelectorAll(".overlay[data-url]:not([ga])").forEach(b=>{ b.setAttribute('ga',1);gtag("event","page_view",{page_title:b.querySelector(".overlay-title").textContent,page_location:b.getAttribute("data-url")})})}}})});document.querySelectorAll(".file-preview").forEach(filePreview=>{filePreview.addEventListener("click",()=>{gtag('event','file_download',{link_url:(new URL(filePreview.getAttribute("href"),window.location.origin)).href, file_name:filePreview.parentNode.querySelector('.file-name').textContent});});});document.querySelectorAll('.shareButtons-button').forEach(shareButton=>{shareButton.addEventListener('click',()=>{gtag('event','share',{method:shareButton.getAttribute('class').match(/.*shareButtons-button--(.*?)$|\s/)[1]});});});document.querySelectorAll('.bookmarkLink:not(.is-bookmarked)').forEach(bookmarkLink=>{bookmarkLink.addEventListener('click',()=>{gtag('event','bookmark');});});document.querySelectorAll(".js-installPromptButton").forEach(a=>{a.addEventListener("click",()=>{gtag("event","app_install_prompt")})});window.addEventListener("appinstalled",()=>{gtag("event","app_install")});XF.PWA&&XF.PWA.isRunning()&&document.addEventListener("visibilitychange",()=>{"visible"===document.visibilityState&&gtag("event","app_open")});setTimeout(()=>{document.querySelectorAll(".adsbygoogle").forEach(a=>{a.addEventListener("mouseenter",()=>{XF.aH=!0});a.addEventListener("mouseleave",()=>{XF.aH=!1});gtag("event","ads_impression",{ad_platform:"adsense"})});["pagehide","blur"].forEach(function(a){window.addEventListener(a,()=>{XF.aH&&gtag("event","ad_click",{ad_platform:"adsense"})},!1)})},3E3);


window.addEventListener('DOMContentLoaded',()=>{XF.Push.updateUserSubscriptionParent=XF.Push.updateUserSubscription;XF.Push.updateUserSubscription=function(b,a){"unsubscribe"===a&&XF.browser.safari&&XF.Push.setPushHistoryUserIds({});XF.Push.updateUserSubscriptionParent(b,a)}});
</script>
<script defer="" src="/js/xf/lightbox-compiled.js?_v=4d9940a3"></script>
<script defer="" src="/js/sv/lazyimageloader/xf/lightbox.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/sv/lazyimageloader/lazy-compiled.js?_v=4d9940a3"></script>
<script defer="" src="/js/xf/action.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/xf/message.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/xf/captcha.min.js?_v=4d9940a3"></script>
<script defer="" src="/js/xf/editor-compiled.js?_v=4d9940a3"></script>
<link href="/styles/next/xenforo/voz-favicon.png?v=3" rel="icon" sizes="32x32" type="image/png"/>

In [12]:
soup.select('h1.p-title-value')[0].text.strip()

'báo lỗi\xa0Hỗ trợ xác thực tài khoản'

In [13]:
soup.select('time.u-dt')[0].text.strip()

'Apr 16, 2025'

In [24]:
id_post = soup.select('a.u-concealed')[1].get('href').split('.')[-1].split('/')[0]

In [30]:
id_post

'1149676'

In [31]:
pagination_one =soup.select('div.block-outer-main')[0].select('li.pageNav-page')

In [32]:
[i.select_one('a').text for i in pagination_one]

['1', '2', '3', '…', '10']

In [33]:
content = soup.select('div.message-inner')

In [34]:
content[0]

<div class="message-inner">
<div class="message-cell message-cell--user">
<section class="message-user">
<div class="message-avatar">
<div class="message-avatar-wrapper">
<a class="avatar avatar--m" data-user-id="1260055" data-xf-init="member-tooltip" href="/u/uniquestz.1260055/" id="js-XFUniqueId5">
<img alt="Uniquestz" class="avatar-u1260055-m" height="96" src="https://data.voz.vn/avatars/m/1260/1260055.jpg?1638723289" srcset="https://data.voz.vn/avatars/l/1260/1260055.jpg?1638723289 2x" width="96"/>
</a>
</div>
</div>
<div class="message-userDetails">
<h4 class="message-name"><a class="username" data-user-id="1260055" data-xf-init="member-tooltip" dir="auto" href="/u/uniquestz.1260055/" id="js-XFUniqueId6">Uniquestz</a></h4>
<h5 class="userTitle message-userTitle" dir="auto">Senior Member</h5>
</div>
<span class="message-userArrow"></span>
</section>
</div>
<div class="message-cell message-cell--main">
<div class="message-main js-quickEditTarget">
<header class="message-attribution message-attribution--split">
<ul class="message-attribution-main listInline">
<li class="u-concealed">
<a href="/t/ho-tro-xac-thuc-tai-khoan.1149676/post-36571220" rel="nofollow">
<time class="u-dt" data-date="Apr 16, 2025" data-short="Apr '25" data-time="4:59 PM" data-timestamp="1744797591" datetime="2025-04-16T16:59:51+0700" dir="auto" title="Apr 16, 2025 at 4:59 PM">Apr 16, 2025</time>
</a>
</li>
</ul>
<ul class="message-attribution-opposite message-attribution-opposite--list">
<li>
<a aria-label="Share" class="message-attribution-gadget" data-href="/p/36571220/share" data-xf-init="share-tooltip" href="/t/ho-tro-xac-thuc-tai-khoan.1149676/post-36571220" id="js-XFUniqueId90" rel="nofollow">
<i class="fa--xf far fa-share-alt"><svg aria-hidden="true" role="img" xmlns="http://www.w3.org/2000/svg"><use href="/data/local/icons/regular.svg?v=1772193142#share-alt"></use></svg></i>
</a>
</li>
<li class="u-hidden js-embedCopy">
<a class="" data-copy-text='&lt;div class="js-xf-embed" data-url="https://voz.vn" data-content="post-36571220"&gt;&lt;/div&gt;&lt;script defer src="https://voz.vn/js/xf/external_embed.js?_v=4d9940a3"&gt;&lt;/script&gt;' data-success="Embed code HTML copied to clipboard." data-xf-init="copy-to-clipboard" href="javascript:">
<i class="fa--xf far fa-code"><svg aria-hidden="true" role="img" xmlns="http://www.w3.org/2000/svg"><use href="/data/local/icons/regular.svg?v=1772193142#code"></use></svg></i>
</a>
</li>
<li>
<a href="/t/ho-tro-xac-thuc-tai-khoan.1149676/post-36571220" rel="nofollow">
						#1
					</a>
</li>
</ul>
</header>
<div class="message-content js-messageContent">
<div class="message-userContent lbContainer js-lbContainer" data-lb-caption-desc="Uniquestz · Apr 16, 2025 at 4:59 PM" data-lb-id="post-36571220">
<article class="message-body js-selectToQuote">
<div>
<div class="bbWrapper">Đã điền đầy đủ thông tin và nhắn cú pháp SMS những vẫn chưa đc xác thực, mod check giúp mình với</div>
</div>
<div class="js-selectToQuoteEnd"> </div>
</article>
</div>
</div>
<footer class="message-footer">
<div class="message-actionBar actionBar">
<div class="actionBar-set actionBar-set--external">
<a class="actionBar-action actionBar-action--reply" data-quote-href="/p/36571220/quote" data-xf-click="quote" href="/t/ho-tro-xac-thuc-tai-khoan.1149676/reply?quote=36571220" rel="nofollow" title="Reply, quoting this message">Reply</a>
</div>
</div>
<div class="reactionsBar js-reactionsList">
</div>
<div class="js-historyTarget message-historyTarget toggleTarget" data-href="trigger-href"></div>
</footer>
</div>
</div>
</div>

In [35]:
id = content[0].select('a.username')[0].get('data-user-id')

In [36]:
user = content[0].select('a.username')[0].text

In [37]:
time = content[0].select('time')[0].get('title')

In [38]:
time

'Apr 16, 2025 at 4:59 PM'

In [39]:
comment  = content[0].select('div.message-content')[0].text.strip()

In [40]:
comment

'Đã điền đầy đủ thông tin và nhắn cú pháp SMS những vẫn chưa đc xác thực, mod check giúp mình với'

In [41]:
all_comment = {'id_post': id_post, 'id_user': id, 'user': user, 'time': time, 'comment': comment}
all_post = {'id_post': id_post, 'title': soup.select('h1.p-title-value')[0].text.strip(), 'time_post': soup.select('time.u-dt')[0].text.strip()}

In [51]:
df_comment = pd.DataFrame(all_comment, index=[0])
df_post = pd.DataFrame(all_post, index=[0])

In [52]:
df_comment

,id_post,id_user,user,time,comment
0,1149676,1260055,Uniquestz,"Apr 16, 2025 at 4:59 PM",Đã điền đầy đủ thông tin và nhắn cú pháp SMS n...

In [49]:
df_post

   id_post                              title     time_post
0  1149676  báo lỗi Hỗ trợ xác thực tài khoản  Apr 16, 2025